/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Fri, 29 Apr 2022 17:31:03 GMT'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    call_to_action: {
      codename: 'call_to_action',
      name: 'Call to Action',
      elements: {
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        subheading: {
          codename: 'subheading',
          name: 'Subheading',
        },
        button_link: {
          codename: 'button_link',
          name: 'Button Link',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        button_image: {
          codename: 'button_image',
          name: 'Button Image',
        },
      },
    },
    hero: {
      codename: 'hero',
      name: 'Hero',
      elements: {
        personalization_criteria: {
          codename: 'personalization_criteria',
          name: 'Personalization Criteria',
        },
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        button_link_slug: {
          codename: 'button_link_slug',
          name: 'Button Link Slug',
        },
      },
    },
    homepage: {
      codename: 'homepage',
      name: 'Homepage',
      elements: {
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
    page: {
      codename: 'page',
      name: 'Page',
      elements: {
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        enrichment_tags: {
          codename: 'enrichment_tags',
          name: 'Enrichment tags',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        components: {
          codename: 'components',
          name: 'Components',
        },
      },
    },
    personalized_heroes: {
      codename: 'personalized_heroes',
      name: 'Personalized Heroes',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        personalized_heroes_list: {
          codename: 'personalized_heroes_list',
          name: 'Personalized Heroes List',
        },
      },
    },
    personalized_talks_lists: {
      codename: 'personalized_talks_lists',
      name: 'Personalized Talks Lists',
      elements: {
        personalized_talks_lists_list: {
          codename: 'personalized_talks_lists_list',
          name: 'Personalized Talks Lists List',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    registration_form: {
      codename: 'registration_form',
      name: 'Registration Form',
      elements: {
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        registered_text: {
          codename: 'registered_text',
          name: 'Registered Text',
        },
      },
    },
    talk: {
      codename: 'talk',
      name: 'Talk',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        audience: {
          codename: 'audience',
          name: 'Audience',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
      },
    },
    talks_list: {
      codename: 'talks_list',
      name: 'Talks List',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        number_to_show: {
          codename: 'number_to_show',
          name: 'Number to Show',
        },
        talks: {
          codename: 'talks',
          name: 'Talks',
        },
        title_when_personalized: {
          codename: 'title_when_personalized',
          name: 'Title when Personalized',
        },
        personalization_criteria: {
          codename: 'personalization_criteria',
          name: 'Personalization Criteria',
        },
        register_button_text: {
          codename: 'register_button_text',
          name: 'Register Button Text',
        },
      },
    },
    why_attend: {
      codename: 'why_attend',
      name: 'Why Attend',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
  },
  taxonomies: {
    taxonomy_categorizing_target_audience: {
      codename: 'taxonomy_categorizing_target_audience',
      name: 'Taxonomy—categorizing target audience',
      terms: {
        for_other_businesses__b2b_: {
          codename: 'for_other_businesses__b2b_',
          name: 'For other businesses (B2B)',
          terms: {},
        },
        for_consumers__b2c_: {
          codename: 'for_consumers__b2c_',
          name: 'For consumers (B2C)',
          terms: {},
        },
      },
    },
  },
};
