import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Fri, 29 Apr 2022 17:31:03 GMT'
 */
export type CallToAction = IContentItem<{
  buttonText: Elements.TextElement;
  subheading: Elements.TextElement;
  buttonLink: Elements.TextElement;
  title: Elements.TextElement;
  buttonImage: Elements.AssetsElement;
}>;
