import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Fri, 29 Apr 2022 17:31:03 GMT'
 */
export type WhyAttend = IContentItem<{
  description: Elements.RichTextElement;
  title: Elements.TextElement;
  image: Elements.AssetsElement;
}>;
